### ISSUE TITLE
Stack level too deep in docker container

### ISSUE THREAD

**Issue by Tall-Paul** [JustinFeng/fakeit#1]
Using this command:

docker run -v 'c:/Users/blah/Desktop/openapi.json:/home/openapi.json' -p 8081:8080 realfengjia/fakeit:latest --spec /home/openapi.json

getting this stack trace:

/usr/local/bundle/gems/openapi_parser-0.3.0/lib/openapi_parser/concerns/findable.rb:31:in `each': stack level too deep (SystemStackError)
        from /usr/local/bundle/gems/openapi_parser-0.3.0/lib/openapi_parser/concerns/findable.rb:31:in `purge_object_cache'
        from /usr/local/bundle/gems/openapi_parser-0.3.0/lib/openapi_parser/concerns/findable.rb:31:in `each'
        from /usr/local/bundle/gems/openapi_parser-0.3.0/lib/openapi_parser/concerns/findable.rb:31:in `purge_object_cache'
        from /usr/local/bundle/gems/openapi_parser-0.3.0/lib/openapi_parser/concerns/findable.rb:31:in `each'
        from /usr/local/bundle/gems/openapi_parser-0.3.0/lib/openapi_parser/concerns/findable.rb:31:in `purge_object_cache'
        from /usr/local/bundle/gems/openapi_parser-0.3.0/lib/openapi_parser/concerns/findable.rb:31:in `each'
        from /usr/local/bundle/gems/openapi_parser-0.3.0/lib/openapi_parser/concerns/findable.rb:31:in `purge_object_cache'
        from /usr/local/bundle/gems/openapi_parser-0.3.0/lib/openapi_parser/concerns/findable.rb:31:in `each'
         ... 11756 levels...
        from /usr/local/bundle/gems/fakeit-0.1.3/lib/fakeit.rb:14:in `build'
        from /usr/local/bundle/gems/fakeit-0.1.3/bin/fakeit:44:in `<top (required)>'
        from /usr/local/bundle/bin/fakeit:23:in `load'
        from /usr/local/bundle/bin/fakeit:23:in `<main>'

**Comment by JustinFeng** [comment]
Hi @Tall-Paul, thank you for your feedback

From the stack trace, looks like it's a runtime error raised from openapi_parser when it tries to resolve json schema `ref`. Potentially could be caused by 

- recursive `ref` in the specification or 
- deep `ref` stack limited by docker image stack size setting

Would you mind provide a specification file (remove any sensitive information), so that I can reproduce this issue locally

**Comment by JustinFeng** [comment]
FYI, random example generation may face the same infinite recursive issue, suggestion will be providing the example for recursive schema and specify `--use-example` option when you run `fakeit` command

**Comment by Tall-Paul** [comment]
Hi Justin, good catch, it was indeed a recursive reference in the definition!  Thanks for your help, I've amended our definition to remove the recursive references which got me past this issue.  I'm now getting another problem, but I'll open another issue for that.

**Comment by JustinFeng** [comment]
Created a monkey patch to fix the recursive schema reference before it get solved in openapi_parser
