### ISSUE TITLE
ERROR NoMethodError: undefined method `to_example' for #

### ISSUE THREAD

**Issue by winterbesos** [JustinFeng/fakeit#20]
when I run fakeit with my doc and run request. the exception be thrown

ERROR NoMethodError: undefined method `to_example' for #<OpenAPIParser::Schemas::Reference:0x00000000017f3c20>\nDid you mean?  to_yaml
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/example/object_example.rb:6:in `block in object_example'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/example/object_example.rb:5:in `each'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/example/object_example.rb:5:in `each_with_object'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/example/object_example.rb:5:in `object_example'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/schema.rb:59:in `type_based_example'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/schema.rb:20:in `to_example'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/schema.rb:36:in `block in all_of_example'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/schema.rb:36:in `map'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/schema.rb:36:in `all_of_example'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/schema.rb:17:in `to_example'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/example/array_example.rb:26:in `generate_items'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/example/array_example.rb:17:in `block in generate_array_example'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/example/array_example.rb:17:in `tap'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/example/array_example.rb:17:in `generate_array_example'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/example/array_example.rb:9:in `array_example'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/schema.rb:59:in `type_based_example'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/schema.rb:20:in `to_example'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/example/object_example.rb:6:in `block in object_example'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/example/object_example.rb:5:in `each'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/example/object_example.rb:5:in `each_with_object'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/example/object_example.rb:5:in `object_example'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/schema.rb:59:in `type_based_example'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/schema.rb:20:in `to_example'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/schema.rb:36:in `block in all_of_example'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/schema.rb:36:in `map'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/schema.rb:36:in `all_of_example'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/schema.rb:17:in `to_example'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/example/object_example.rb:6:in `block in object_example'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/example/object_example.rb:5:in `each'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/example/object_example.rb:5:in `each_with_object'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/example/object_example.rb:5:in `object_example'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/schema.rb:59:in `type_based_example'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/schema.rb:20:in `to_example'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/schema.rb:36:in `block in all_of_example'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/schema.rb:36:in `map'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/schema.rb:36:in `all_of_example'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/schema.rb:17:in `to_example'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/openapi/operation.rb:24:in `body'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/app/routes/openapi_route.rb:26:in `response'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/app/routes/openapi_route.rb:19:in `handle'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/app/routes/openapi_route.rb:12:in `block in call'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/app/routes/openapi_route.rb:12:in `then'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/app/routes/openapi_route.rb:12:in `call'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/app/app_builder.rb:17:in `block in build'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/middleware/recorder.rb:11:in `block in call'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/middleware/recorder.rb:11:in `then'
	/usr/local/rvm/gems/ruby-2.7.0/gems/fakeit-0.7.0/lib/fakeit/middleware/recorder.rb:11:in `call'
	/usr/local/rvm/gems/ruby-2.7.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
	/usr/local/rvm/gems/ruby-2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:244:in `call'
	/usr/local/rvm/gems/ruby-2.7.0/gems/rack-2.2.3/lib/rack/handler/webrick.rb:95:in `service'
	/usr/local/rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/webrick/httpserver.rb:140:in `service'
	/usr/local/rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/webrick/httpserver.rb:96:in `run'
	/usr/local/rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/webrick/server.rb:307:in `block in start_thread'

**Comment by JustinFeng** [comment]
Hi @winterbesos , thank you for report the issue, would you mind provide a example spec file that can be used to reproduce the issue, cheers

**Comment by JustinFeng** [comment]
Make some progress on this, seems the error occurs when a `$ref` attribute cannot be expanded, maybe due to an invalid url/path. It's more like a issue of the spec file itself, but I will put in some change to provide a more friendly error message
