### ISSUE TITLE
camelCase instead of PascalCase

### ISSUE THREAD

**Issue by afsharm** [JustinFeng/fakeit#22]
Hello,

Is there any option to force **fakeit** to generate json member names as camelCase instead of PascalCase? For instance, generate item.title instead of item.Title (consider letter T)

**Comment by ahx** [comment]
@afsharm I don’t know if fakeit has an option for this, but I am curious about your use case. Can you explain? Do you want a fake-response that differs compared to what is described in the API description? If yes, why? I just want to learn about more use cases / problems with Openapi mocks in general.

**Comment by afsharm** [comment]
@ahx Thanks for your question. It lead me to find that the problem is not the **fakeit**. I did not notice that my openAPI sepc is PascalCase itself. So it make sense if it generate json results as PascalCase too. 
So why I was expecting camelCase? Because my real back-end is ASP.NET Core, and AFAIK it produces camelCase results by default.
Anyway thank for the answer.
