### ISSUE TITLE
"Tried to load unspecified class: Date" error is given when spec contains a text that resembles a date

### ISSUE THREAD

**Issue by ahmeturun** [JustinFeng/fakeit#25]
When there is a text in the openapi specification that looks like a date, an error is given as below. Looked around and found an issue that looks related with an underlying library https://github.com/ruby/psych/issues/262
example spec to reproduce: [petstore.zip](https://github.com/JustinFeng/fakeit/files/6949708/petstore.zip)

> C:/Ruby30-x64/lib/ruby/3.0.0/psych/class_loader.rb:99:in `find': Tried to load unspecified class: Date (Psych::DisallowedClass)
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/class_loader.rb:28:in `load'
        from (eval):2:in `date'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/scalar_scanner.rb:60:in `tokenize'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:64:in `deserialize'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:127:in `visit_Psych_Nodes_Scalar'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/visitor.rb:30:in `visit'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/visitor.rb:6:in `accept'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:34:in `accept'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:336:in `block in register_empty'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:336:in `each'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:336:in `register_empty'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:145:in `visit_Psych_Nodes_Sequence'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/visitor.rb:30:in `visit'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/visitor.rb:6:in `accept'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:34:in `accept'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:343:in `block in revive_hash'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:341:in `each'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:341:in `each_slice'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:341:in `revive_hash'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:166:in `visit_Psych_Nodes_Mapping'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/visitor.rb:30:in `visit'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/visitor.rb:6:in `accept'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:34:in `accept'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:343:in `block in revive_hash'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:341:in `each'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:341:in `each_slice'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:341:in `revive_hash'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:166:in `visit_Psych_Nodes_Mapping'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/visitor.rb:30:in `visit'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/visitor.rb:6:in `accept'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:34:in `accept'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:343:in `block in revive_hash'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:341:in `each'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:341:in `each_slice'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:341:in `revive_hash'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:166:in `visit_Psych_Nodes_Mapping'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/visitor.rb:30:in `visit'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/visitor.rb:6:in `accept'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:34:in `accept'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:343:in `block in revive_hash'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:341:in `each'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:341:in `each_slice'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:341:in `revive_hash'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:166:in `visit_Psych_Nodes_Mapping'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/visitor.rb:30:in `visit'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/visitor.rb:6:in `accept'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:34:in `accept'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:343:in `block in revive_hash'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:341:in `each'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:341:in `each_slice'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:341:in `revive_hash'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:166:in `visit_Psych_Nodes_Mapping'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/visitor.rb:30:in `visit'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/visitor.rb:6:in `accept'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:34:in `accept'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:343:in `block in revive_hash'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:341:in `each'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:341:in `each_slice'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:341:in `revive_hash'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:166:in `visit_Psych_Nodes_Mapping'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/visitor.rb:30:in `visit'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/visitor.rb:6:in `accept'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:34:in `accept'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:317:in `visit_Psych_Nodes_Document'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/visitor.rb:30:in `visit'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/visitor.rb:6:in `accept'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:34:in `accept'
        from C:/Ruby30-x64/lib/ruby/3.0.0/psych.rb:361:in `safe_load'
        from <internal:kernel>:124:in `then'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/fakeit-0.9.1/lib/fakeit/openapi/loader.rb:9:in `load'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/fakeit-0.9.1/lib/fakeit/openapi/specification.rb:7:in `initialize'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/fakeit-0.9.1/lib/fakeit/app/routes/openapi_route.rb:5:in `new'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/fakeit-0.9.1/lib/fakeit/app/routes/openapi_route.rb:5:in `initialize'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/fakeit-0.9.1/lib/fakeit/app/app_builder.rb:6:in `new'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/fakeit-0.9.1/lib/fakeit/app/app_builder.rb:6:in `initialize'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/fakeit-0.9.1/lib/fakeit.rb:18:in `new'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/fakeit-0.9.1/lib/fakeit.rb:18:in `block in build'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/fakeit-0.9.1/lib/fakeit.rb:17:in `new'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/fakeit-0.9.1/lib/fakeit.rb:17:in `build'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/fakeit-0.9.1/bin/fakeit:55:in `<top (required)>'
        from C:/Ruby30-x64/bin/fakeit:23:in `load'
        from C:/Ruby30-x64/bin/fakeit:23:in `<main>'

**Comment by JustinFeng** [comment]
Hi @ahmeturun, firstly thank you for submitting the issue, I confirm I can reproduce it

I did some investigation around the yaml loading logic in Ruby, the root cause is Ruby will try to parse those Date/DateTime-like value in yaml if you don't force it to be a string type(by adding quotes)

[Here](https://stackoverflow.com/questions/19109912/yaml-do-i-need-quotes-for-strings-in-yaml#:~:text=In%20general%2C%20you%20don't%20need%20quotes.,%25%20%2C%20%40%20%2C%20%5C%20).) is also some discussion talking about it will be good to explicitly add quotes when the value contains special characters

What I will do is to allow fakeit to successfully parse the given yaml example, but it also means the example won't be interpreted as string literal, instead it will become a Date/DateTime object, it's actually fine for Date-like string, as when it's serialised to String, it will be exactly the same.

However, my suggest for the workaround are
- Add quotes to those value with special characters, or
- Use spec in json format

Another side note about the spec file, I believe you specified the `tag` field as `string`, but in your example, you actually provided an array

**Comment by JustinFeng** [comment]
0.9.2 is released
