### ISSUE TITLE
End to End Tests

### ISSUE THREAD

**Issue by philsturgeon** [JustinFeng/fakeit#8]
Howdy! Working on [Prism](https://stoplight.io/prism) we created a [whooooole bunch of end to end tests](https://github.com/stoplightio/prism/tree/master/test-harness/specs), covering content negotiation, static and dynamic mocking, using x-faker, example selection, loads of stuff. If you want to grab some of these tests, or even reuse our format for e2e testing CLI commands, go right ahead. :)

**Comment by JustinFeng** [comment]
Hi @philsturgeon, thank you for your suggestion, and I really like your work in Prism.
Fakeit is still in a very early stage, at the moment, I'm trying to cover most of the test case in unit test level and just keep minimum amount of api test to verify integration. However, I reckon those e2e tests will definitely help with enriching my api test scenarios. Cheers
