### ISSUE TITLE
Support .yaml files

### ISSUE THREAD

**Issue by monsterkrampe** [JustinFeng/fakeit#9]
https://github.com/JustinFeng/fakeit/blob/d893dcedf59342dfc3c7935674ad7113a5927616/lib/fakeit/openapi/loader.rb#L19

It's awesome that fakeit supports both `.json` and `.yml` files.
I think that `.yaml` should also be mapped to YAML :)

**Comment by JustinFeng** [comment]
Good catch, pr merged
